from datetime import datetime

from app.config import DEFAULT_ADMIN_PASSWORD, DEFAULT_ADMIN_USERNAME
from app.database.connection import get_connection
from app.database.sql import normalize_datetime
from app.utils.security import hash_password, verify_password


SCHEMA_SQL = """
CREATE TABLE IF NOT EXISTS users (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    first_name TEXT NOT NULL,
    last_name TEXT NOT NULL,
    dni TEXT NOT NULL,
    password_hash TEXT NOT NULL,
    role TEXT NOT NULL DEFAULT 'employee'
        CHECK (role IN ('admin', 'employee')),
    active BOOLEAN NOT NULL DEFAULT TRUE,
    last_business_id TEXT,
    created_at TIMESTAMP WITHOUT TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS businesses (
    id TEXT PRIMARY KEY,
    owner_user_id INTEGER NOT NULL,
    business_name TEXT NOT NULL,
    business_type TEXT NOT NULL,
    login_code TEXT NOT NULL,
    slug TEXT NOT NULL,
    business_key TEXT NOT NULL,
    settings_json TEXT NOT NULL DEFAULT '{}',
    last_accessed_at TIMESTAMP WITHOUT TIME ZONE,
    is_active BOOLEAN NOT NULL DEFAULT TRUE,
    created_at TIMESTAMP WITHOUT TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP WITHOUT TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP,
    FOREIGN KEY (owner_user_id) REFERENCES users(id)
);

CREATE UNIQUE INDEX IF NOT EXISTS idx_users_dni_lower
ON users(LOWER(dni));

CREATE UNIQUE INDEX IF NOT EXISTS idx_businesses_login_code_active
ON businesses(LOWER(login_code))
WHERE is_active IS TRUE;

CREATE UNIQUE INDEX IF NOT EXISTS idx_businesses_slug
ON businesses(slug);

CREATE UNIQUE INDEX IF NOT EXISTS idx_businesses_business_key
ON businesses(business_key);

CREATE INDEX IF NOT EXISTS idx_businesses_owner
ON businesses(owner_user_id);

CREATE TABLE IF NOT EXISTS business_members (
    business_id TEXT NOT NULL,
    user_id INTEGER NOT NULL,
    member_role TEXT NOT NULL DEFAULT 'employee'
        CHECK (member_role IN ('owner', 'admin', 'employee')),
    is_default BOOLEAN NOT NULL DEFAULT FALSE,
    joined_at TIMESTAMP WITHOUT TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP,
    last_accessed_at TIMESTAMP WITHOUT TIME ZONE,
    PRIMARY KEY (business_id, user_id),
    FOREIGN KEY (business_id) REFERENCES businesses(id),
    FOREIGN KEY (user_id) REFERENCES users(id)
);

CREATE INDEX IF NOT EXISTS idx_business_members_user
ON business_members(user_id, is_default, last_accessed_at);

CREATE INDEX IF NOT EXISTS idx_business_members_business
ON business_members(business_id, member_role);

CREATE TABLE IF NOT EXISTS attendance_sessions (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    business_id TEXT,
    user_id INTEGER NOT NULL,
    clock_in_time TIMESTAMP WITHOUT TIME ZONE NOT NULL,
    clock_out_time TIMESTAMP WITHOUT TIME ZONE,
    is_active BOOLEAN NOT NULL DEFAULT TRUE,
    total_seconds INTEGER,
    notes TEXT,
    exit_note TEXT,
    incident_type TEXT,
    created_at TIMESTAMP WITHOUT TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP,
    closed_by_admin BOOLEAN NOT NULL DEFAULT FALSE,
    manual_close_reason TEXT,
    closed_by_user_id INTEGER,
    FOREIGN KEY (user_id) REFERENCES users(id)
);

CREATE UNIQUE INDEX IF NOT EXISTS idx_attendance_sessions_one_active
ON attendance_sessions(COALESCE(business_id, ''), user_id)
WHERE is_active IS TRUE;

CREATE INDEX IF NOT EXISTS idx_attendance_sessions_user_clock_in
ON attendance_sessions(user_id, clock_in_time);

CREATE INDEX IF NOT EXISTS idx_attendance_sessions_clock_in
ON attendance_sessions(clock_in_time);

CREATE TABLE IF NOT EXISTS employees (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    first_name TEXT,
    last_name TEXT,
    name TEXT NOT NULL,
    username TEXT NOT NULL,
    password_hash TEXT NOT NULL,
    role TEXT NOT NULL DEFAULT 'employee'
        CHECK (role IN ('admin', 'employee')),
    active BOOLEAN NOT NULL DEFAULT TRUE,
    created_at TIMESTAMP WITHOUT TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS time_entries (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    business_id TEXT,
    employee_id INTEGER NOT NULL,
    entry_type TEXT NOT NULL
        CHECK (entry_type IN ('entrada', 'salida')),
    timestamp TIMESTAMP WITHOUT TIME ZONE NOT NULL,
    notes TEXT,
    created_at TIMESTAMP WITHOUT TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP,
    FOREIGN KEY (employee_id) REFERENCES employees(id)
);

CREATE UNIQUE INDEX IF NOT EXISTS idx_employees_username_lower
ON employees(LOWER(username));

CREATE INDEX IF NOT EXISTS idx_time_entries_employee_timestamp
ON time_entries(employee_id, timestamp);

CREATE INDEX IF NOT EXISTS idx_time_entries_timestamp
ON time_entries(timestamp);

CREATE TABLE IF NOT EXISTS work_schedules (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    business_id TEXT,
    name TEXT NOT NULL,
    description TEXT,
    weekly_hours_target REAL,
    is_active BOOLEAN NOT NULL DEFAULT TRUE,
    created_at TIMESTAMP WITHOUT TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP WITHOUT TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE INDEX IF NOT EXISTS idx_work_schedules_business
ON work_schedules(business_id, is_active);

CREATE TABLE IF NOT EXISTS schedule_days (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    schedule_id INTEGER NOT NULL,
    day_of_week SMALLINT NOT NULL,
    start_time TIME WITHOUT TIME ZONE NOT NULL,
    end_time TIME WITHOUT TIME ZONE NOT NULL,
    break_minutes SMALLINT NOT NULL DEFAULT 0,
    late_tolerance_minutes SMALLINT NOT NULL DEFAULT 0,
    early_leave_tolerance_minutes SMALLINT NOT NULL DEFAULT 0,
    UNIQUE (schedule_id, day_of_week),
    FOREIGN KEY (schedule_id) REFERENCES work_schedules(id) ON DELETE CASCADE
);

CREATE TABLE IF NOT EXISTS employee_schedules (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id INTEGER NOT NULL,
    schedule_id INTEGER NOT NULL,
    business_id TEXT,
    effective_from DATE NOT NULL,
    effective_to DATE,
    is_active BOOLEAN NOT NULL DEFAULT TRUE,
    created_at TIMESTAMP WITHOUT TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP,
    FOREIGN KEY (user_id) REFERENCES users(id),
    FOREIGN KEY (schedule_id) REFERENCES work_schedules(id) ON DELETE RESTRICT
);

CREATE INDEX IF NOT EXISTS idx_employee_schedules_user
ON employee_schedules(user_id, is_active);

CREATE INDEX IF NOT EXISTS idx_employee_schedules_schedule
ON employee_schedules(schedule_id);

CREATE TABLE IF NOT EXISTS employee_profiles (
    user_id INTEGER PRIMARY KEY,
    hire_date DATE,
    contract_type TEXT,
    department TEXT,
    job_title TEXT,
    phone TEXT,
    personal_email TEXT,
    emergency_contact_name TEXT,
    emergency_contact_phone TEXT,
    social_security_number TEXT,
    notes TEXT,
    created_at TIMESTAMP WITHOUT TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP WITHOUT TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP,
    FOREIGN KEY (user_id) REFERENCES users(id) ON DELETE CASCADE
);

"""


def initialize_database() -> None:
    with get_connection() as connection:
        connection.execute("SELECT pg_advisory_xact_lock(%s)", (2_026_041_400,))
        _execute_schema(connection)
        _migrate_business_foundation(connection)
        _migrate_legacy_employee_columns(connection)
        _migrate_users_from_legacy_employees(connection)
        _ensure_default_admin(connection)
        _sync_users_to_legacy_employees(connection)
        _migrate_attendance_sessions_from_time_entries(connection)
        _migrate_attendance_sessions_add_context_columns(connection)
        _migrate_attendance_sessions_add_admin_close_columns(connection)
        _migrate_scheduling_tables(connection)
        _migrate_work_schedules_schedule_type(connection)
        _migrate_employee_profiles_table(connection)
        _reset_identity_sequences(connection)


def _execute_schema(connection) -> None:
    """
    Execute schema statements one by one.

    psycopg does not execute multi-statement schema strings with bound params.
    Splitting keeps initialization explicit and easy to debug.
    """
    for statement in SCHEMA_SQL.split(";"):
        clean_statement = statement.strip()
        if clean_statement:
            connection.execute(clean_statement)


def _table_columns(connection, table_name: str) -> set[str]:
    rows = connection.execute(
        """
        SELECT column_name
        FROM information_schema.columns
        WHERE table_schema = CURRENT_SCHEMA()
          AND table_name = %s
        """,
        (table_name,),
    ).fetchall()
    return {row["column_name"] for row in rows}


def _migrate_business_foundation(connection) -> None:
    """Add SaaS business context columns to older local databases."""
    user_columns = _table_columns(connection, "users")
    if "last_business_id" not in user_columns:
        connection.execute("ALTER TABLE users ADD COLUMN last_business_id TEXT")

    session_columns = _table_columns(connection, "attendance_sessions")
    if "business_id" not in session_columns:
        connection.execute("ALTER TABLE attendance_sessions ADD COLUMN business_id TEXT")
    connection.execute("DROP INDEX IF EXISTS idx_attendance_sessions_one_active")
    connection.execute(
        """
        CREATE UNIQUE INDEX IF NOT EXISTS idx_attendance_sessions_one_active
        ON attendance_sessions(COALESCE(business_id, ''), user_id)
        WHERE is_active IS TRUE
        """
    )
    connection.execute(
        """
        CREATE INDEX IF NOT EXISTS idx_attendance_sessions_business_clock_in
        ON attendance_sessions(business_id, clock_in_time)
        """
    )

    time_entry_columns = _table_columns(connection, "time_entries")
    if "business_id" not in time_entry_columns:
        connection.execute("ALTER TABLE time_entries ADD COLUMN business_id TEXT")
    connection.execute(
        """
        CREATE INDEX IF NOT EXISTS idx_time_entries_business_timestamp
        ON time_entries(business_id, timestamp)
        """
    )


def _migrate_legacy_employee_columns(connection) -> None:
    """
    Keep older databases working after splitting employees.name into
    first_name and last_name.
    """
    columns = _table_columns(connection, "employees")
    had_name_column = "name" in columns

    if "first_name" not in columns:
        connection.execute("ALTER TABLE employees ADD COLUMN first_name TEXT")
    if "last_name" not in columns:
        connection.execute("ALTER TABLE employees ADD COLUMN last_name TEXT")
    if "name" not in columns:
        connection.execute("ALTER TABLE employees ADD COLUMN name TEXT")
    if "created_at" not in columns:
        connection.execute(
            "ALTER TABLE employees ADD COLUMN created_at TIMESTAMP WITHOUT TIME ZONE"
        )

    if had_name_column:
        connection.execute(
            """
            UPDATE employees
            SET first_name = CASE
                    WHEN first_name IS NOT NULL AND TRIM(first_name) <> ''
                        THEN TRIM(first_name)
                    WHEN POSITION(' ' IN TRIM(name)) > 0
                        THEN TRIM(SUBSTRING(TRIM(name) FROM 1 FOR POSITION(' ' IN TRIM(name)) - 1))
                    ELSE COALESCE(NULLIF(TRIM(name), ''), username)
                END,
                last_name = CASE
                    WHEN last_name IS NOT NULL AND TRIM(last_name) <> ''
                        THEN TRIM(last_name)
                    WHEN POSITION(' ' IN TRIM(name)) > 0
                        THEN TRIM(SUBSTRING(TRIM(name) FROM POSITION(' ' IN TRIM(name)) + 1))
                    ELSE ''
                END
            WHERE first_name IS NULL
               OR TRIM(first_name) = ''
               OR last_name IS NULL
            """
        )
    else:
        connection.execute(
            """
            UPDATE employees
            SET first_name = COALESCE(NULLIF(TRIM(first_name), ''), username),
                last_name = COALESCE(last_name, '')
            WHERE first_name IS NULL
               OR TRIM(first_name) = ''
               OR last_name IS NULL
            """
        )

    connection.execute(
        """
        UPDATE employees
        SET name = TRIM(COALESCE(first_name, '') || ' ' || COALESCE(last_name, ''))
        WHERE name IS NULL OR TRIM(name) = ''
        """
    )

    connection.execute(
        """
        UPDATE employees
        SET created_at = COALESCE(created_at, CURRENT_TIMESTAMP)
        WHERE created_at IS NULL
        """
    )


def _migrate_users_from_legacy_employees(connection) -> None:
    rows = connection.execute(
        """
        SELECT id, first_name, last_name, username, password_hash, role, active, created_at
        FROM employees
        ORDER BY id
        """
    ).fetchall()

    for row in rows:
        first_name = (row["first_name"] or row["username"] or "").strip()
        last_name = (row["last_name"] or "").strip()
        dni = (row["username"] or "").strip()
        if not dni:
            continue

        connection.execute(
            """
            INSERT INTO users
                (id, first_name, last_name, dni, password_hash, role, active, created_at)
            VALUES (%s, %s, %s, %s, %s, %s, %s, COALESCE(%s, CURRENT_TIMESTAMP))
            ON CONFLICT DO NOTHING
            """,
            (
                row["id"],
                first_name,
                last_name,
                dni,
                row["password_hash"],
                row["role"],
                row["active"],
                row["created_at"],
            ),
        )


def _ensure_default_admin(connection) -> None:
    admin = connection.execute(
        """
        SELECT id, password_hash
        FROM users
        WHERE LOWER(dni) = LOWER(%s) AND role = 'admin'
        LIMIT 1
        """,
        (DEFAULT_ADMIN_USERNAME,),
    ).fetchone()

    if admin:
        stored_hash = admin["password_hash"]
        if verify_password("admin123", stored_hash) and not verify_password(
            DEFAULT_ADMIN_PASSWORD,
            stored_hash,
        ):
            connection.execute(
                "UPDATE users SET password_hash = %s WHERE id = %s",
                (hash_password(DEFAULT_ADMIN_PASSWORD), admin["id"]),
            )
        return

    connection.execute(
        """
        INSERT INTO users
            (first_name, last_name, dni, password_hash, role, active)
        VALUES (%s, %s, %s, %s, 'admin', TRUE)
        """,
        (
            "Admin",
            "Sistema",
            DEFAULT_ADMIN_USERNAME,
            hash_password(DEFAULT_ADMIN_PASSWORD),
        ),
    )


def _sync_users_to_legacy_employees(connection) -> None:
    rows = connection.execute(
        """
        SELECT id, first_name, last_name, dni, password_hash, role, active, created_at
        FROM users
        ORDER BY id
        """
    ).fetchall()

    for row in rows:
        name = f"{row['first_name']} {row['last_name']}".strip()
        connection.execute(
            """
            INSERT INTO employees
                (id, first_name, last_name, name, username, password_hash, role, active, created_at)
            VALUES (%s, %s, %s, %s, %s, %s, %s, %s, COALESCE(%s, CURRENT_TIMESTAMP))
            ON CONFLICT DO NOTHING
            """,
            (
                row["id"],
                row["first_name"],
                row["last_name"],
                name,
                row["dni"],
                row["password_hash"],
                row["role"],
                row["active"],
                row["created_at"],
            ),
        )
        connection.execute(
            """
            UPDATE employees
            SET first_name = %s,
                last_name = %s,
                name = %s,
                username = %s,
                password_hash = %s,
                role = %s,
                active = %s,
                created_at = COALESCE(created_at, %s)
            WHERE id = %s
            """,
            (
                row["first_name"],
                row["last_name"],
                name,
                row["dni"],
                row["password_hash"],
                row["role"],
                row["active"],
                row["created_at"],
                row["id"],
            ),
        )


def _migrate_attendance_sessions_from_time_entries(connection) -> None:
    existing = connection.execute(
        "SELECT COUNT(*) AS count FROM attendance_sessions"
    ).fetchone()["count"]
    if existing:
        return

    rows = connection.execute(
        """
        SELECT employee_id, entry_type, timestamp, notes
        FROM time_entries
        ORDER BY employee_id, timestamp, id
        """
    ).fetchall()

    active_by_user: dict[int, int] = {}
    active_started_at: dict[int, str] = {}

    for row in rows:
        user_id = row["employee_id"]
        entry_type = row["entry_type"]
        timestamp = row["timestamp"]

        user_exists = connection.execute(
            "SELECT 1 FROM users WHERE id = %s",
            (user_id,),
        ).fetchone()
        if not user_exists:
            continue

        if entry_type == "entrada" and user_id not in active_by_user:
            cursor = connection.execute(
                """
                INSERT INTO attendance_sessions
                    (user_id, clock_in_time, is_active, notes)
                VALUES (%s, %s, TRUE, %s)
                RETURNING id
                """,
                (user_id, timestamp, row["notes"]),
            )
            active_by_user[user_id] = int(cursor.fetchone()["id"])
            active_started_at[user_id] = normalize_datetime(timestamp)
            continue

        if entry_type == "salida" and user_id in active_by_user:
            started_at = active_started_at[user_id]
            total_seconds = _seconds_between(started_at, timestamp)
            connection.execute(
                """
                UPDATE attendance_sessions
                SET clock_out_time = %s,
                    is_active = FALSE,
                    total_seconds = %s,
                    notes = COALESCE(notes, %s)
                WHERE id = %s
                """,
                (timestamp, total_seconds, row["notes"], active_by_user[user_id]),
            )
            del active_by_user[user_id]
            del active_started_at[user_id]


def _migrate_attendance_sessions_add_admin_close_columns(connection) -> None:
    """Add admin-close audit columns to attendance_sessions if they don't exist yet."""
    columns = _table_columns(connection, "attendance_sessions")
    if "closed_by_admin" not in columns:
        connection.execute(
            "ALTER TABLE attendance_sessions ADD COLUMN closed_by_admin BOOLEAN NOT NULL DEFAULT FALSE"
        )
    if "manual_close_reason" not in columns:
        connection.execute(
            "ALTER TABLE attendance_sessions ADD COLUMN manual_close_reason TEXT"
        )
    if "closed_by_user_id" not in columns:
        connection.execute(
            "ALTER TABLE attendance_sessions ADD COLUMN closed_by_user_id INTEGER"
        )


def _migrate_attendance_sessions_add_context_columns(connection) -> None:
    """Add exit context columns to attendance_sessions if they don't exist yet."""
    columns = _table_columns(connection, "attendance_sessions")
    if "exit_note" not in columns:
        connection.execute("ALTER TABLE attendance_sessions ADD COLUMN exit_note TEXT")
    if "incident_type" not in columns:
        connection.execute("ALTER TABLE attendance_sessions ADD COLUMN incident_type TEXT")


def _migrate_scheduling_tables(connection) -> None:
    """Add scheduling tables if they don't exist yet (idempotent)."""
    # work_schedules
    connection.execute(
        """
        CREATE TABLE IF NOT EXISTS work_schedules (
            id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
            business_id TEXT,
            name TEXT NOT NULL,
            description TEXT,
            weekly_hours_target REAL,
            is_active BOOLEAN NOT NULL DEFAULT TRUE,
            created_at TIMESTAMP WITHOUT TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP,
            updated_at TIMESTAMP WITHOUT TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP
        )
        """
    )
    connection.execute(
        """
        CREATE INDEX IF NOT EXISTS idx_work_schedules_business
        ON work_schedules(business_id, is_active)
        """
    )

    # schedule_days
    connection.execute(
        """
        CREATE TABLE IF NOT EXISTS schedule_days (
            id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
            schedule_id INTEGER NOT NULL,
            day_of_week SMALLINT NOT NULL,
            start_time TIME WITHOUT TIME ZONE NOT NULL,
            end_time TIME WITHOUT TIME ZONE NOT NULL,
            break_minutes SMALLINT NOT NULL DEFAULT 0,
            late_tolerance_minutes SMALLINT NOT NULL DEFAULT 0,
            early_leave_tolerance_minutes SMALLINT NOT NULL DEFAULT 0,
            UNIQUE (schedule_id, day_of_week),
            FOREIGN KEY (schedule_id) REFERENCES work_schedules(id) ON DELETE CASCADE
        )
        """
    )

    # employee_schedules
    connection.execute(
        """
        CREATE TABLE IF NOT EXISTS employee_schedules (
            id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
            user_id INTEGER NOT NULL,
            schedule_id INTEGER NOT NULL,
            business_id TEXT,
            effective_from DATE NOT NULL,
            effective_to DATE,
            is_active BOOLEAN NOT NULL DEFAULT TRUE,
            created_at TIMESTAMP WITHOUT TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP,
            FOREIGN KEY (user_id) REFERENCES users(id),
            FOREIGN KEY (schedule_id) REFERENCES work_schedules(id) ON DELETE RESTRICT
        )
        """
    )
    connection.execute(
        """
        CREATE INDEX IF NOT EXISTS idx_employee_schedules_user
        ON employee_schedules(user_id, is_active)
        """
    )
    connection.execute(
        """
        CREATE INDEX IF NOT EXISTS idx_employee_schedules_schedule
        ON employee_schedules(schedule_id)
        """
    )


def _migrate_work_schedules_schedule_type(connection) -> None:
    """Add schedule_type column to work_schedules if not present."""
    columns = _table_columns(connection, "work_schedules")
    if "schedule_type" not in columns:
        connection.execute(
            """
            ALTER TABLE work_schedules
            ADD COLUMN schedule_type TEXT NOT NULL DEFAULT 'flexible'
            """
        )
    # Enforce CHECK constraint safely (add index for clarity, not hard constraint to stay idempotent)
    connection.execute(
        """
        UPDATE work_schedules
        SET schedule_type = 'flexible'
        WHERE schedule_type NOT IN ('flexible', 'strict')
        """
    )


def _migrate_employee_profiles_table(connection) -> None:
    """Create employee_profiles table if it doesn't exist yet."""
    connection.execute(
        """
        CREATE TABLE IF NOT EXISTS employee_profiles (
            user_id INTEGER PRIMARY KEY,
            hire_date DATE,
            contract_type TEXT,
            department TEXT,
            job_title TEXT,
            phone TEXT,
            personal_email TEXT,
            emergency_contact_name TEXT,
            emergency_contact_phone TEXT,
            social_security_number TEXT,
            notes TEXT,
            created_at TIMESTAMP WITHOUT TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP,
            updated_at TIMESTAMP WITHOUT TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP,
            FOREIGN KEY (user_id) REFERENCES users(id) ON DELETE CASCADE
        )
        """
    )


def _reset_identity_sequences(connection) -> None:
    for table_name in (
        "users", "employees", "attendance_sessions", "time_entries",
        "work_schedules", "schedule_days", "employee_schedules",
    ):
        connection.execute(
            f"""
            SELECT setval(
                pg_get_serial_sequence('{table_name}', 'id'),
                COALESCE((SELECT MAX(id) FROM {table_name}), 0) + 1,
                FALSE
            )
            """
        )


def _seconds_between(start, end) -> int:
    try:
        started = (
            start if isinstance(start, datetime) else datetime.fromisoformat(str(start))
        )
        ended = end if isinstance(end, datetime) else datetime.fromisoformat(str(end))
    except (TypeError, ValueError):
        return 0
    return max(int((ended - started).total_seconds()), 0)
